export const BRC_DATA_CATALOG_CATEGORY_KEY = {
  ACCESSION: "accession",
  ANALYZE_GENOME: "analyzeGenome",
  ANNOTATION_STATUS: "annotationStatus",
  ASSEMBLY_COUNT: "assemblyCount",
  ASSEMBLY_TAXONOMY_IDS: "assemblyTaxonomyIds",
  BIOSAMPLE: "biosample",
  CHROMOSOMES: "chromosomes",
  COVERAGE: "coverage",
  GC_PERCENT: "gcPercent",
  INSTRUMENT: "instrument",
  IS_REF: "isRef",
  LENGTH: "length",
  LEVEL: "level",
  LIBRARY_LAYOUT: "library_layout",
  LIBRARY_SOURCE: "library_source",
  LIBRARY_STRATEGY: "library_strategy",
  MAX_SCAFFOLD_N50: "maxScaffoldN50",
  PLATFORM: "platform",
  RUN_TOTAL_BASES: "runTotalBases",
  SCAFFOLD_COUNT: "scaffoldCount",
  SCAFFOLD_L50: "scaffoldL50",
  SCAFFOLD_N50: "scaffoldN50",
  SPECIES: "species",
  SRA_ACCESSION: "sraSubmission",
  SRP_ACCESSION: "sraStudy",
  SRR_ACCESSION: "sraRun",
  SRS_ACCESSION: "sraSample",
  SRX_ACCESSION: "sraExperiment",
  STRAIN: "strain",
  TAXONOMIC_GROUP: "taxonomicGroup",
  TAXONOMY_ID: "ncbiTaxonomyId",
  TOTAL_BASES: "totalBases",
  UCSC_BROWSER_URL: "ucscBrowserUrl",
};

export const BRC_DATA_CATALOG_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ANALYZE_GENOME: "Action",
  ANNOTATION_STATUS: "Annotation Status",
  ASSEMBLY_COUNT: "Assemblies",
  ASSEMBLY_TAXONOMY_IDS: "Taxonomy ID",
  BIOSAMPLE: "BioSample",
  CHROMOSOMES: "Chromosomes",
  COVERAGE: "Coverage",
  GC_PERCENT: "GC%",
  INSTRUMENT: "Instrument",
  IS_REF: "Is Ref",
  LENGTH: "Length",
  LEVEL: "Level",
  LIBRARY_LAYOUT: "Library Layout",
  LIBRARY_SOURCE: "Library Source",
  LIBRARY_STRATEGY: "Library Strategy",
  MAX_SCAFFOLD_N50: "N50",
  PLATFORM: "Platform",
  RUN_TOTAL_BASES: "#Run Bases",
  SCAFFOLD_COUNT: "Scaffolds",
  SCAFFOLD_L50: "Scaffold L50",
  SCAFFOLD_N50: "Scaffold N50",
  SPECIES: "Species",
  SRA_ACCESSION: "Submission",
  SRP_ACCESSION: "Study",
  SRR_ACCESSION: "Run",
  SRS_ACCESSION: "Sample",
  SRX_ACCESSION: "Experiment",
  STRAIN: "Strain",
  TAXONOMIC_GROUP: "Taxonomic Group",
  TAXONOMY_ID: "Taxonomy ID",
  TOTAL_BASES: "#Bases",
  UCSC_BROWSER_URL: "UCSC Browser",
};
